---
title: "Lab 3"
theme: solar
format:
  html:
    code-fold: true
    self-contained: true
jupyter: python3
---

In [27]:
import pandas as pd
import numpy as np
xmas = pd.read_csv("https://www.dropbox.com/scl/fi/qxaslqqp5p08i1650rpc4/xmas.csv?rlkey=erdxi7jbh7pqf9fh4lv4cayp5&dl=1")

# Function 1: Pluralize_Gift

In [28]:
xmas

    Day Day.in.Words  Gift.Item        Verb Adjective        Location
0     1        first  partridge         NaN       NaN  in a pear tree
1     2       second       dove         NaN    turtle             NaN
2     3        third        hen         NaN    french             NaN
3     4       fourth       bird         NaN   calling             NaN
4     5        fifth       ring         NaN    golden             NaN
5     6        sixth      goose    a-laying       NaN             NaN
6     7      seventh       swan  a-swimming       NaN             NaN
7     8       eighth       maid   a-milking       NaN             NaN
8     9        ninth       lady     dancing       NaN             NaN
9    10        tenth       lord   a-leaping       NaN             NaN
10   11     eleventh      piper      piping       NaN             NaN
11   12      twelfth    drummer    drumming       NaN             NaN

In [30]:
def pluralize_gift(gift):
    """
    Returns plural of a noun

    Parameters
    ----------
    gift: str
    A noun

    Return
    ------
    str
    Plural version
    """
    
    #Do a couple checks for outlier grammar changes to a plural word
    if gift.find("oo") != -1:
        gift = gift.replace("oo","ee")
    elif gift.find("y") == (len(gift)-1): #The y must be indexed at the final char to change plural
        gift = gift.replace("y","ie")
    #Add the required s for plurals
    gift += "s"

    return gift

In [31]:
#Adding in a plurals column of each item
xmas['Plurals'] = xmas.apply(lambda x: pluralize_gift(x['Gift.Item']), axis=1)

# Function 2: Make_Phrase

In [32]:
#Adding a column for column of number in word form to use in final text
xmas["Num.in.Words"] = xmas["Day"].map({
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve"
})

xmas

,Day,Day.in.Words,Gift.Item,Verb,Adjective,Location,Plurals,Num.in.Words
0,1,first,partridge,NaN,NaN,in a pear tree,partridges,one
1,2,second,dove,NaN,turtle,NaN,doves,two
2,3,third,hen,NaN,french,NaN,hens,three
3,4,fourth,bird,NaN,calling,NaN,birds,four
4,5,fifth,ring,NaN,golden,NaN,rings,five
5,6,sixth,goose,a-laying,NaN,NaN,geeses,six
6,7,seventh,swan,a-swimming,NaN,NaN,swans,seven
7,8,eighth,maid,a-milking,NaN,NaN,maids,eight
8,9,ninth,lady,dancing,NaN,NaN,ladies,nine
9,10,tenth,lord,a-leaping,NaN,NaN,lords,ten
10,11,eleventh,piper,piping,NaN,NaN,pipers,eleven
11,12,twelfth,drummer,drumming,NaN,NaN,drummers,twelve

In [38]:
def make_phrase(num, num_word, item, verb, adjective, location):
    """
    Returns one phrase of the song

    Parameters
    ----------
    num: numeric
    number of that gift
    
    num_word: str
    word string of num
    
    item: str
    noun word of the gift item
    
    adjective: str
    an adjective of the item
    
    location: str
    noun describing the place of the item

    Return
    ------
    str
    Phrase
    """
    ## Step 1: Replace NAs with blank strings
    
    #Stepping through each of verb, adjective, and locatioon which may be missing in a line
    #And replacing nan values with empty strings
    #Could have done this tidier with a loop, but I'm afraid of using loops on this assignment!
    if type(verb) != str:
        if np.isnan(verb):
            verb = ""
    if type(adjective) != str:
        if np.isnan(adjective):
            adjective = ""
    if type(location) != str:
        if np.isnan(location):
            location = ""

    ## Step 2: If the day number is larger than 1, the gift items need pluralized!
    ### Hint: call the function you created above!

    if num > 1:
        item = pluralize_gift(item)

    ## Step 3: Figure out if a gift item starts with a vowel
    
    #Create a simple flag indicating if the gift starts with a vowel
    flag_vowel = False
    #Check if the lowercase of the first letter in the string for the gift is a vowel
    if item[0].lower() in ('a','e','i','o','u'):
        flag_vowel = True
        
    ## Step 4: For the first day, if the gift item starts with a vowel,
    #replace the day with "an" and if the gift item does not start with a vowel,
    #replace the day with "a" (e.g. a partridge in a pear tree).
    #If it is not the first day, use just the number word (e.g. ten lords a leap)

    if num == 1:
        if flag_vowel:
            num = "an"
        else:
            num = "a"
    else:
        num = num_word
        
    
    ## Step 5: Put all of the pieces together into one string and return!
    phrase = ""
    phrase += num
    if adjective != "":
        phrase += " " + adjective
    phrase += " " + item
    if verb != "":
        phrase += " " + verb
    if location != "":
        phrase += " " + location
    return phrase

In [53]:
ind = 11
make_phrase(xmas["Day"].iloc[ind], xmas["Num.in.Words"].iloc[ind], xmas["Gift.Item"].iloc[ind], xmas["Verb"].iloc[ind], xmas["Adjective"].iloc[ind], xmas["Location"].iloc[ind])

'twelve drummers drumming'

In [54]:
#Prepping the next function by creating a phrase column per day
xmas['Full.Phrase'] = xmas.apply(lambda x: make_phrase(x["Day"], x["Num.in.Words"], x["Gift.Item"], x["Verb"], x["Adjective"], x["Location"]), axis=1)
xmas

,Day,Day.in.Words,Gift.Item,Verb,Adjective,Location,Plurals,Num.in.Words,Full.Phrase
0,1,first,partridge,NaN,NaN,in a pear tree,partridges,one,a partridge in a pear tree
1,2,second,dove,NaN,turtle,NaN,doves,two,two turtle doves
2,3,third,hen,NaN,french,NaN,hens,three,three french hens
3,4,fourth,bird,NaN,calling,NaN,birds,four,four calling birds
4,5,fifth,ring,NaN,golden,NaN,rings,five,five golden rings
5,6,sixth,goose,a-laying,NaN,NaN,geeses,six,six geeses a-laying
6,7,seventh,swan,a-swimming,NaN,NaN,swans,seven,seven swans a-swimming
7,8,eighth,maid,a-milking,NaN,NaN,maids,eight,eight maids a-milking
8,9,ninth,lady,dancing,NaN,NaN,ladies,nine,nine ladies dancing
9,10,tenth,lord,a-leaping,NaN,NaN,lords,ten,ten lords a-leaping
10,11,eleventh,piper,piping,NaN,NaN,pipers,eleven,eleven pipers piping
11,12,twelfth,drummer,drumming,NaN,NaN,drummers,twelve,twelve drummers drumming

# Function 3: Sing Day

In [70]:
def sing_day(dataset, num, phrase_col):
    """
    Returns one whole day of the song

    Parameters
    ----------
    dataset: dataframe
    the full song dataframe split into word columns
    
    num: numeric
    integer of the day
    
    phrase_col: str
    The name of a column in the dataset that contains the phrases for each day
    

    Return
    ------
    str
    Entire verse of that particular day. Note, printing is necessary to get proper formatting.
    """
  
    # Step 1: Setup the intro line
    num_word = dataset["Day.in.Words"].iloc[num-1]
    intro = "On the " + num_word + " day of Christmas, my true love sent to me:\n"

    # Step 2: Sing the gift phrases
    # Hint: What order are the gifts sung in each day?
    gifts = ""
    for i in range(num-1,-1,-1): #Tracking from index num-1 to index 0, decrementing each step by 1
        gifts += dataset[phrase_col].iloc[i]
        if i != 0:
            gifts += ","
            if i == 1:
                gifts += " and\n"
            else:
                gifts+= "\n"
        else:
            gifts += "."

    # Step 3: Put it all together and return
    return str(intro + gifts)

In [75]:
a = sing_day(xmas,3,'Full.Phrase')
print(a)

On the third day of Christmas, my true love sent to me:
three french hens,
two turtle doves, and
a partridge in a pear tree.

In [76]:
a = sing_day(xmas,12,'Full.Phrase')
print(a)

On the twelfth day of Christmas, my true love sent to me:
twelve drummers drumming,
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

# Full song

In [78]:
#We'll use a loop here to pass through each day of the song and print the output
for i in range(1,13):
    print(sing_day(xmas,i,'Full.Phrase') + "\n")

On the first day of Christmas, my true love sent to me:
a partridge in a pear tree.

On the second day of Christmas, my true love sent to me:
two turtle doves, and
a partridge in a pear tree.

On the third day of Christmas, my true love sent to me:
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the fourth day of Christmas, my true love sent to me:
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the fifth day of Christmas, my true love sent to me:
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the sixth day of Christmas, my true love sent to me:
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the seventh day of Christmas, my true love sent to me:
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the eighth day of Christmas, my true love sent to me:
eight maids a-milking,
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the ninth day of Christmas, my true love sent to me:
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the tenth day of Christmas, my true love sent to me:
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the eleventh day of Christmas, my true love sent to me:
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

On the twelfth day of Christmas, my true love sent to me:
twelve drummers drumming,
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geeses a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves, and
a partridge in a pear tree.

# New song

In [79]:
xmas2 = pd.read_csv("https://www.dropbox.com/scl/fi/p9x9k8xwuzs9rhp582vfy/xmas_2.csv?rlkey=kvc3j3lmyn4opcidsrhcmrof1&dl=1")

In [81]:
#Adding in a plurals column of each item
xmas2['Plurals'] = xmas2.apply(lambda x: pluralize_gift(x['Gift.Item']), axis=1)

#Adding a column for column of number in word form to use in final text
xmas2["Num.in.Words"] = xmas2["Day"].map({
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve"
})

#Prepping the sing_day function by creating a phrase column per day
xmas2['Full.Phrase'] = xmas2.apply(lambda x: make_phrase(x["Day"], x["Num.in.Words"], x["Gift.Item"], x["Verb"], x["Adjective"], x["Location"]), axis=1)

for i in range(1,13):
    print(sing_day(xmas2,i,'Full.Phrase') + "\n")

On the first day of Christmas, my true love sent to me:
an email from Cal Poly.

On the second day of Christmas, my true love sent to me:
two meal points, and
an email from Cal Poly.

On the third day of Christmas, my true love sent to me:
three lost pens,
two meal points, and
an email from Cal Poly.

On the fourth day of Christmas, my true love sent to me:
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the fifth day of Christmas, my true love sent to me:
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the sixth day of Christmas, my true love sent to me:
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the seventh day of Christmas, my true love sent to me:
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the eighth day of Christmas, my true love sent to me:
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the ninth day of Christmas, my true love sent to me:
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the tenth day of Christmas, my true love sent to me:
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the eleventh day of Christmas, my true love sent to me:
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.

On the twelfth day of Christmas, my true love sent to me:
twelve hours sleeping,
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points, and
an email from Cal Poly.